apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 192.168.1.169:443/project/frontend:10.13
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: GUESTBOOK_API_ADDR
          value: "backend:8000"
      imagePullSecrets:
        - name: harbor-credential
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8000
    nodePort: 30227
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 192.168.1.169:443/project/backend:10.13
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: GUESTBOOK_DB_ADDR
          value: "mongodb:17017"
      imagePullSecrets:
        - name: harbor-credential
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: 192.168.1.169:443/project/mongodb:3.1
        ports:
        - containerPort: 27017
      imagePullSecrets:
        - name: harbor-credential
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 17017
    targetPort: 27017
  type: ClusterIP
